In [73]:
import numpy as np
import pandas as pd
# Banking data: Customer_ID, Account_Balance, Credit_Score, Transaction_Count, Years_Active
banking_data = np.array([
    [101, 5000, 720, 45, 3],
    [102, 12000, 680, 52, 5],
    [103, 2500, 610, 12, 1],
    [104, 7800, 790, 67, 4],
    [105, 3000, 550, 8, 2],
    [106, 16000, 845, 89, 6],
    [107, 4000, 700, 35, 2],
    [108, 980, 600, 22, 1],
    [109, 22000, 890, 103, 8],
    [110, 500, 430, 5, 3]
])

print("\nORIGINAL BANKING DATA:")
print(banking_data)
print(f"\nData shape: {banking_data.shape}")
print(f"Data type: {banking_data.dtype}")


ORIGINAL BANKING DATA:
[[  101  5000   720    45     3]
 [  102 12000   680    52     5]
 [  103  2500   610    12     1]
 [  104  7800   790    67     4]
 [  105  3000   550     8     2]
 [  106 16000   845    89     6]
 [  107  4000   700    35     2]
 [  108   980   600    22     1]
 [  109 22000   890   103     8]
 [  110   500   430     5     3]]

Data shape: (10, 5)
Data type: int64



### Question 1: Array Creation and Manipulation

In [ ]:
# Q1.1:Create a 4x4 identity matrix using np.eye()

matrix = np.eye(4)
print(matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [3]:
# Q1.2:Create an array of 8 zeros using np.zeros()

zeros = np.zeros(8)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# Q1.3:Create an array of 6 ones using np.ones()

ones = np.ones(6)
print(ones)

[1. 1. 1. 1. 1. 1.]


In [6]:

# Q1.4: Create an array with values from 0 to 15 using np.arange()

range = np.arange(0,16)
print(range)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [7]:
# Q1.5: Create an array with 8 evenly spaced values from 0 to 100 using np.linspace()

evenly_space = np.linspace(0,100,8)
print(evenly_space)

[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


### Question 2: Array Attributes and Information

In [10]:
# Q2.1: What is the shape of the banking_data array?

print(f"shape:{banking_data.shape}")

shape:(10, 5)


In [11]:

# Q2.2: What is the data type of the banking_data array?

print(f"Data type: {banking_data.dtype}")

Data type: int64


In [12]:

# Q2.3: What is the size (total number of elements) of the banking_data array?

print(f"Size: {banking_data.size}")

Size: 50


In [13]:

# Q2.4: What is the number of dimensions of the banking_data array?

print(f"dimension:{banking_data.ndim}")

dimension:2


In [14]:
# Q2.5: What is the memory size of the banking_data array in bytes?

print(f"size:{banking_data.nbytes}")

size:400


In [3]:
# Q3.1: Extract the first row of banking_data
print(banking_data[0])

[ 101 5000  720   45    3]


In [4]:
# Q3.2: Extract the last row of banking_data
print(banking_data[-1])
     

[110 500 430   5   3]


In [5]:
# Q3.3: Extract the Account_Balance column (column index 1)
print(banking_data[:,1])

[ 5000 12000  2500  7800  3000 16000  4000   980 22000   500]


In [6]:
# Q3.4: Extract the first 4 rows and first 3 columns
print(banking_data[:4,:3])

[[  101  5000   720]
 [  102 12000   680]
 [  103  2500   610]
 [  104  7800   790]]


In [7]:
# Q3.5: Extract rows 3 to 7 (inclusive)
print(banking_data[3:8,:])

[[  104  7800   790    67     4]
 [  105  3000   550     8     2]
 [  106 16000   845    89     6]
 [  107  4000   700    35     2]
 [  108   980   600    22     1]]


In [10]:
# Q4.1: Calculate the sum of all account balances
sum_account = np.sum(banking_data[:,1])
print(sum_account)

73780


In [11]:
# Q4.2: Calculate the mean account balance
mean_account = np.mean(banking_data[:,1])
print(mean_account)

7378.0


In [12]:
# Q4.3: Calculate the standard deviation of account balances
std_account = np.std(banking_data[:,1])
print(std_account)

6767.211833539719


In [13]:
# Q4.4: Calculate the variance of account balances
var_account = np.var(banking_data[:,1])
print(var_account)

45795156.0


In [14]:
# Q4.5: Calculate the median account balance
median_account = np.median(banking_data[:,1])
print(median_account)

4500.0


In [15]:
# Q5.1: Find the minimum and maximum account balances
min_account = np.min(banking_data[:,1])
max_account = np.max(banking_data[:,1])
print(f"min_account:{min_account},max_account:{max_account}")

min_account:500,max_account:22000


In [16]:
# Q5.2: Find the minimum and maximum credit scores
min_Credit = np.min(banking_data[:,2])
max_Credit = np.max(banking_data[:,2])
print(f"min_Credit:{min_Credit},max_Credit:{max_Credit}")

min_Credit:430,max_Credit:890


In [17]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
per_values = np.percentile(banking_data[:,1],[25,50,75])
print(per_values[0],per_values[1],per_values[2])

2625.0 4500.0 10950.0


In [18]:
# Q5.4: Calculate the correlation between account balance and credit score
cor_relation = np.corrcoef(banking_data[:,1],banking_data[:,2])[0,1]
print(cor_relation)
     

0.8372661040710151


In [19]:
# Q5.5: Calculate the covariance between account balance and credit score
covar = np.cov(banking_data[:,1],banking_data[:,2])[0,1]
print(covar)

835436.6666666666


In [20]:
# Q6.1: Reshape the banking_data to 5 rows × 10 columns
reshaping_bdata = np.reshape(banking_data,(5,10))
print(reshaping_bdata)

[[  101  5000   720    45     3   102 12000   680    52     5]
 [  103  2500   610    12     1   104  7800   790    67     4]
 [  105  3000   550     8     2   106 16000   845    89     6]
 [  107  4000   700    35     2   108   980   600    22     1]
 [  109 22000   890   103     8   110   500   430     5     3]]


In [21]:
# Q6.2: Flatten the banking_data to a 1D array
flattening_bdata = banking_data.flatten()
print(flattening_bdata)

[  101  5000   720    45     3   102 12000   680    52     5   103  2500
   610    12     1   104  7800   790    67     4   105  3000   550     8
     2   106 16000   845    89     6   107  4000   700    35     2   108
   980   600    22     1   109 22000   890   103     8   110   500   430
     5     3]


In [22]:
# Q6.3: Transpose the banking_data
trans = banking_data.T
print(trans)

[[  101   102   103   104   105   106   107   108   109   110]
 [ 5000 12000  2500  7800  3000 16000  4000   980 22000   500]
 [  720   680   610   790   550   845   700   600   890   430]
 [   45    52    12    67     8    89    35    22   103     5]
 [    3     5     1     4     2     6     2     1     8     3]]


In [23]:
# Q6.4: Split the banking_data into 2 equal parts vertically
split_bd = np.vsplit(banking_data,2)
print(split_bd[0])
print(split_bd[1])

[[  101  5000   720    45     3]
 [  102 12000   680    52     5]
 [  103  2500   610    12     1]
 [  104  7800   790    67     4]
 [  105  3000   550     8     2]]
[[  106 16000   845    89     6]
 [  107  4000   700    35     2]
 [  108   980   600    22     1]
 [  109 22000   890   103     8]
 [  110   500   430     5     3]]


In [38]:
# Q6.5: Split the banking_data into 2 equal parts horizontally

split_hs = np.array_split(banking_data, 2, axis=1)
print(split_hs[0])
print(split_hs[1])

[[  101  5000   720]
 [  102 12000   680]
 [  103  2500   610]
 [  104  7800   790]
 [  105  3000   550]
 [  106 16000   845]
 [  107  4000   700]
 [  108   980   600]
 [  109 22000   890]
 [  110   500   430]]
[[ 45   3]
 [ 52   5]
 [ 12   1]
 [ 67   4]
 [  8   2]
 [ 89   6]
 [ 35   2]
 [ 22   1]
 [103   8]
 [  5   3]]


In [39]:
# Q7.1: Find customers with account balance greater than $100,000
data = banking_data[banking_data[:,1]> 100000]
print(data)

[]


In [40]:
# Q7.2: Find customers with credit score greater than 800
data = banking_data[banking_data[:,2]> 800]
print(data)

[[  106 16000   845    89     6]
 [  109 22000   890   103     8]]


In [41]:
# # Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
data = banking_data[(banking_data[:,3] > 50) & (banking_data[:,2] < 750)]
print(data)

[[  102 12000   680    52     5]]


In [42]:
# Q7.4: Count how many customers have account balance between 
100,000
data = np.sum((banking_data[:,1]>=10000) & (banking_data[:,1] <=100000))
print(data)

3


In [43]:
# Q7.5: Find the index of the customer with the highest credit score
data = np.argmax(banking_data[:,2])+1
print(data)

9


In [44]:
# Q8.1: Sort the banking_data by account balance (ascending)
data = banking_data[banking_data[:,1].argsort()]
data

array([[  110,   500,   430,     5,     3],
       [  108,   980,   600,    22,     1],
       [  103,  2500,   610,    12,     1],
       [  105,  3000,   550,     8,     2],
       [  107,  4000,   700,    35,     2],
       [  101,  5000,   720,    45,     3],
       [  104,  7800,   790,    67,     4],
       [  102, 12000,   680,    52,     5],
       [  106, 16000,   845,    89,     6],
       [  109, 22000,   890,   103,     8]])

In [45]:
# Q8.2: Sort the banking_data by credit score (descending)
data = banking_data[(-banking_data[:,2]).argsort()]
print(data)


[[  109 22000   890   103     8]
 [  106 16000   845    89     6]
 [  104  7800   790    67     4]
 [  101  5000   720    45     3]
 [  107  4000   700    35     2]
 [  102 12000   680    52     5]
 [  103  2500   610    12     1]
 [  108   980   600    22     1]
 [  105  3000   550     8     2]
 [  110   500   430     5     3]]


In [46]:
# Q8.3: Find the indices that would sort the array by years active
data = np.argsort(banking_data[:,4])
print(data)

[2 7 4 6 0 9 3 1 5 8]


In [47]:
# Q8.4: Find the customer with the second highest account balance
data1 = np.argsort(banking_data[:,1])[-2]
data = banking_data[data1]
print(data[0])

106


In [48]:
# Q8.5: Find the customer with the lowest transaction count
data1 = np.argmin(banking_data[:,3])
print(data[0])

106


In [49]:
# Q9.1: Calculate the absolute values of all elements
data = np.abs(banking_data)
print(data)

[[  101  5000   720    45     3]
 [  102 12000   680    52     5]
 [  103  2500   610    12     1]
 [  104  7800   790    67     4]
 [  105  3000   550     8     2]
 [  106 16000   845    89     6]
 [  107  4000   700    35     2]
 [  108   980   600    22     1]
 [  109 22000   890   103     8]
 [  110   500   430     5     3]]


In [50]:
# Q9.2: Calculate the square root of all account balances
data = np.sqrt(banking_data[:,1])
print(data)

[ 70.71067812 109.5445115   50.          88.31760866  54.77225575
 126.49110641  63.2455532   31.30495168 148.32396974  22.36067977]


In [51]:
# Q9.3: Calculate the square of all credit scores
data = np.square(banking_data[:,2])
print(data)

[518400 462400 372100 624100 302500 714025 490000 360000 792100 184900]


In [52]:
# Q9.4: Calculate the exponential of all transaction counts
data = np.exp(banking_data[:,3])
print(data)

[3.49342711e+19 3.83100800e+22 1.62754791e+05 1.25236317e+29
 2.98095799e+03 4.48961282e+38 1.58601345e+15 3.58491285e+09
 5.39922761e+44 1.48413159e+02]


In [53]:
# Q9.5: Calculate the natural logarithm of all account balances
data = np.log(banking_data[:,1])
print(data)

[8.51719319 9.39266193 7.82404601 8.96187901 8.00636757 9.680344
 8.29404964 6.88755257 9.99879773 6.2146081 ]


In [54]:
# Q10.1: Calculate the cumulative sum of account balances
data = np.cumsum(banking_data[:,1])
print(data)

[ 5000 17000 19500 27300 30300 46300 50300 51280 73280 73780]


In [55]:
# Q10.2: Calculate the cumulative product of transaction counts
data = np.cumprod(banking_data[:,3])
print(data)

[             45            2340           28080         1881360
        15050880      1339528320     46883491200   1031436806400
 106237991059200 531189955296000]


In [56]:
# Q10.3: Calculate the difference between consecutive account balances
data = np.diff(banking_data[:,1])
print(data)

[  7000  -9500   5300  -4800  13000 -12000  -3020  21020 -21500]


In [57]:
# Q10.4: Calculate the gradient of account balances
data = np.gradient(banking_data[:,1])
print(data)

[  7000.  -1250.  -2100.    250.   4100.    500.  -7510.   9000.   -240.
 -21500.]


In [58]:
# Q10.5: Calculate the histogram of account balances with 5 bins
hist,hist_bins = np.histogram(banking_data[:,1], bins = 5)
print(hist)
print(hist_bins)

[5 2 1 1 1]
[  500.  4800.  9100. 13400. 17700. 22000.]


In [59]:
# Q11.1: Generate 6 random integers between 1 and 1000
import numpy as np
data = np.random.randint(1,1001,6)
print(data)

[599 667 333 112 306 524]


In [60]:
# Q11.2: Generate 6 random floats between 0 and 1
data = np.random.random(6)
print(data)

[0.3808307  0.56001499 0.50240221 0.97857286 0.93868822 0.34870077]


In [61]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
data = np.random.normal(700,100,6)
print(data)

[508.48905258 821.23115522 760.907544   694.2265457  596.65512282
 692.15483226]


In [62]:
# Q11.4: Shuffle the banking_data rows randomly
shuffled_data = banking_data.copy()
np.random.shuffle(shuffled_data)
print(shuffled_data)

[[  108   980   600    22     1]
 [  110   500   430     5     3]
 [  103  2500   610    12     1]
 [  101  5000   720    45     3]
 [  105  3000   550     8     2]
 [  106 16000   845    89     6]
 [  104  7800   790    67     4]
 [  107  4000   700    35     2]
 [  102 12000   680    52     5]
 [  109 22000   890   103     8]]


In [63]:
# Q11.5: Set random seed to 123 and generate 4 random numbersdata
np.random.seed(123)
seeded_random = np.random.random(4)
print(seeded_random)

[0.69646919 0.28613933 0.22685145 0.55131477]


In [64]:
# Q12.1: Calculate the dot product of account balance and credit score columns
dot_product = np.dot(banking_data[:, 1], banking_data[:, 2])
print(dot_product)

57800000


In [65]:
# Q12.2: Calculate the cross product of first two rows
cross_product = np.cross(banking_data[0, :3], banking_data[1, :3])
print(cross_product)

[-5240000     4760   702000]


In [66]:
# Q12.3: Calculate the norm (magnitude) of the account balance column
banking_data = np.linalg.norm(banking_data[:, 1])
print(data)

[508.48905258 821.23115522 760.907544   694.2265457  596.65512282
 692.15483226]


In [67]:
# Q12.4: Create a 3x3 matrix and calculate its determinant
matrix_3x3 = np.array([[2, 3, 4], [1, 4, 8], [6, 7, 3]])
determinant = np.linalg.det(matrix_3x3)
print(matrix_3x3)
print(determinant)

[[2 3 4]
 [1 4 8]
 [6 7 3]]
-20.99999999999999


In [68]:
# Q12.5: Calculate the inverse of the 3x3 matrix
data = np.linalg.inv(matrix_3x3)
print(data)

[[ 2.0952381  -0.9047619  -0.38095238]
 [-2.14285714  0.85714286  0.57142857]
 [ 0.80952381 -0.19047619 -0.23809524]]


In [75]:
# Q13.1: Convert all customer IDs to strings
customer_ids_str = banking_data[:, 0].astype(str)
print(customer_ids_str)

['101' '102' '103' '104' '105' '106' '107' '108' '109' '110']


In [76]:
# Q13.2: Check if any customer ID contains '100'
data = np.char.find(customer_ids_str, '100') >= 0
print(banking_data[data])

[]


In [77]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)
data = np.char.upper(customer_ids_str)
print(data)
     

['101' '102' '103' '104' '105' '106' '107' '108' '109' '110']


In [78]:
# Q13.4: Count the length of each customer ID string
data = np.char.str_len(customer_ids_str)
print(data)

[3 3 3 3 3 3 3 3 3 3]


In [79]:
# Q13.5: Replace '10' with 'CUST' in customer IDs
data = np.char.replace(customer_ids_str, '10', 'CUST')
print(data)

['CUST1' 'CUST2' 'CUST3' 'CUST4' 'CUST5' 'CUST6' 'CUST7' 'CUST8' 'CUST9'
 '1CUST']


In [80]:
# Q14.1: Convert years active to months
yrs_to_months = banking_data[:, 4] * 12
print(yrs_to_months)

[36 60 12 48 24 72 24 12 96 36]


In [81]:
# Q14.2: Calculate the average years active
avg_yrs = np.mean(banking_data[:, 4])
print(avg_yrs)

3.5


In [82]:
# Q14.3: Find customers who have been active for more than 15 years
yrs_active = banking_data[banking_data[:, 4] > 15]
print(yrs_active)

[]


In [83]:
# Q14.4: Calculate the total time all customers have been active (in years)
total_active_time = np.sum(banking_data[:, 4])
print(total_active_time)

35


In [84]:
# Q14.5: Find the customer with the shortest time active
customer_short_active= np.argmin(banking_data[:, 4])
shortest_customer_active = banking_data[customer_short_active]
print(f"customer ID: {customer_short_active}, Days: {shortest_customer_active}")

customer ID: 2, Days: [ 103 2500  610   12    1]


In [85]:
# Q15.1: Apply a function to calculate 5% interest on all account balances
import numpy as np

def add_interest(balance):
    return balance * 1.05  

interest_applied = np.vectorize(add_interest)(banking_data[:, 1])
print(interest_applied)

[ 5250. 12600.  2625.  8190.  3150. 16800.  4200.  1029. 23100.   525.]


In [87]:
# Q15.2: Use np.where to categorize customers by balance ranges
balances = banking_data[:,1]
customers_balance =  np.where(balances < 15000, "Low",
              np.where(balances < 45000, "Medium", "High"))
print(customers_balance)

['Low' 'Low' 'Low' 'Low' 'Low' 'Medium' 'Low' 'Low' 'Medium' 'Low']


In [88]:
# Q15.3: Use np.select to categorize customers by credit score ranges
conditions = [
    banking_data[:, 4] < 9,
    (banking_data[:, 4] >= 15) & (banking_data[:, 4] < 20),
    banking_data[:, 4] >= 20
]
choices = ['poor', 'Mid-range', 'good']
cus_credit_score = np.select(conditions, choices, default='Unknown')
print(cus_credit_score)

['poor' 'poor' 'poor' 'poor' 'poor' 'poor' 'poor' 'poor' 'poor' 'poor']


In [89]:
# Q15.4: Use np.piecewise to apply different interest rates based on balance
def low_interest(x): return x * 1.05
def mid_interest(x): return x * 1.10
def high_interest(x): return x * 1.20

interest_prices = np.piecewise(
    banking_data[:, 1],
    [banking_data[:, 1] < 20000, (banking_data[:, 1] >= 20000) & (banking_data[:, 1] < 25000), banking_data[:, 1] >= 25000],
    [low_interest, mid_interest, high_interest]
)
print(interest_prices)

[ 5250 12600  2625  8190  3150 16800  4200  1029 24200   525]


In [90]:
# Q15.5: Use np.apply_along_axis to calculate the sum of each row
row_sums = np.apply_along_axis(np.sum, 1, banking_data)
print(row_sums)

[ 5869 12839  3226  8765  3665 17046  4844  1711 23110  1048]


In [91]:
# Q16.1: Concatenate two arrays horizontally using np.hstack()
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
con_array = np.hstack([array1,array2])
print(con_array)

[1 2 3 4 5 6]


In [92]:
# Q16.2: Concatenate two arrays vertically using np.vstack()
vcon_array = np.vstack([array1,array2])
print(vcon_array)

[[1 2 3]
 [4 5 6]]


In [93]:
# Q16.3: Concatenate arrays along a specific axis using np.concatenate()
import numpy as np
data = np.concatenate([array1,array2],axis = 0)
print(data)

[1 2 3 4 5 6]


In [94]:
# Q16.4: Stack arrays depth-wise using np.dstack()
data = np.dstack([array1,array2])
print(data)

[[[1 4]
  [2 5]
  [3 6]]]


In [95]:
# Q16.5: Create a column stack using np.column_stack()
data = np.column_stack([array1,array2])
print(data)

[[1 4]
 [2 5]
 [3 6]]


In [96]:
# Q17.1: Split an array into 3 equal parts using np.split()
array = np.array([1,2,3,4,5,6])
split_array = np.split(array,3)
for i, part in enumerate(split_array):
  print(f"Parts[{i+1}] = {part} ")

Parts[1] = [1 2] 
Parts[2] = [3 4] 
Parts[3] = [5 6] 


In [97]:
# Q17.2: Split an array at specific indices using np.split()
array = np.array([1,2,3,4,5,6])
split_array = np.split(array,[2,8])
print(split_array)

[array([1, 2]), array([3, 4, 5, 6]), array([], dtype=int64)]


In [98]:
# Q17.3: Split an array horizontally using np.hsplit()
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
hsplit_parts = np.hsplit(arr_2d, 3)
print(hsplit_parts)

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [99]:
# Q17.4: Split an array vertically using np.vsplit()
vsplit_parts = np.vsplit(arr_2d, 2)
print(f"Vertical parts:{vsplit_parts}")

Vertical parts:[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [100]:
# Q17.5: Split an array into equal chunks using np.array_split()
chunks = np.array_split(array, 4)
print(f"Split into 4 chunks:{chunks}")

Split into 4 chunks:[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [101]:
# Q18.1: Repeat each element of an array 3 times using np.repeat()
import numpy as np
elements = np.repeat(array1,3)
print(elements)

[1 1 1 2 2 2 3 3 3]


In [102]:
# Q18.2: Repeat an entire array 2 times using np.tile()
elements = np.tile(array1,2)
print(elements)

[1 2 3 1 2 3]


In [ ]:
# # Q18.3: Repeat a 2D array using np.tile()
# ar = np.array([[5,6],[7,8]])
# tile = np.tile(ar,(4,4))
# print(f"Original array:{ar}")
# print(f"Tile:{tile}")


Original array:[[5 6]
 [7 8]]
Tile:[[5 6 5 6 5 6 5 6]
 [7 8 7 8 7 8 7 8]
 [5 6 5 6 5 6 5 6]
 [7 8 7 8 7 8 7 8]
 [5 6 5 6 5 6 5 6]
 [7 8 7 8 7 8 7 8]
 [5 6 5 6 5 6 5 6]
 [7 8 7 8 7 8 7 8]]


In [104]:
# Q18.4:Create a pattern using np.tile()
pattern = np.array([1,2,3,4])
tile = np.tile(pattern,6)
print(f"original array:{pattern}")
print(f"Tile:{tile}")

original array:[1 2 3 4]
Tile:[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]


In [105]:
# Q18.5: Repeat elements with different counts using np.repeat()
array = np.array([4,5,6])
repeat_counts = [2,3,5]
repeat_var = np.repeat(array,repeat_counts)
print(f"original array:{array}")
print(f"Repeat count:{repeat_counts}")
print(f"Repeat Var:{repeat_var}")

original array:[4 5 6]
Repeat count:[2, 3, 5]
Repeat Var:[4 4 5 5 5 6 6 6 6 6]


In [106]:
# Q19.1: Compare two arrays for equality using np.array_equal()
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])
print(f"arr a:{a}")
print(f"arr b:{b}")
print(f"arr c:{c}")
print(f"Array a equals b:{np.array_equal(a,b)}")
print(f"Array b equals c:{np.array_equal(b,c)}")

arr a:[1 2 3]
arr b:[4 5 6]
arr c:[7 8 9]
Array a equals b:False
Array b equals c:False


In [ ]:
# Q19.2: Check if arrays are close using np.allclose()

arr1 = np.array([1.0, 2.0, 3.000001])
arr2 = np.array([1.0, 2.0, 3.0])

result = np.allclose(arr1, arr2)

print("Are arrays close?:", result)


Are arrays close?: True


In [108]:
# Q19.3: Apply logical AND operation between arrays
logical_and = np.logical_and(a > 1, a < 3)
print(f"Array: {b}")
print(f"Logical AND (1 < x < 3): {logical_and}")

Array: [4 5 6]
Logical AND (1 < x < 3): [False  True False]


In [109]:
# Q19.4: Apply logical OR operation between arrays

import numpy as np

arr1 = np.array([True, False, True, False])
arr2 = np.array([False, False, True, True])

result = np.logical_or(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Logical OR result:", result)


Array 1: [ True False  True False]
Array 2: [False False  True  True]
Logical OR result: [ True False  True  True]


In [111]:
# Q19.5: Apply logical NOT operation to an array
arr = np.array([0, 1, 2, 0])
result = np.logical_not(arr)

print("Original:", arr)
print("Logical NOT:", result)


Original: [0 1 2 0]
Logical NOT: [ True False False  True]


In [112]:
# Q20.1: Find unique elements in an array using np.unique()
duplicate_array = np.array([2,2,3,3,4,5,6,6,6,])
unique = np.unique(duplicate_array)
print(f"Duplicate Array:{duplicate_array}")
print(f"Unique:{unique}")

Duplicate Array:[2 2 3 3 4 5 6 6 6]
Unique:[2 3 4 5 6]


In [113]:
# Q20.2: Find the intersection of two arrays using np.intersect1d()
a1 = np.array([1,2,3,4,5])
a2 = np.array([4,5,6])
intersection = np.intersect1d(a1,a2)
print(f"A1:{a1}")
print(f"A2:{a2}")
print(f"Intersection:{intersection}")

A1:[1 2 3 4 5]
A2:[4 5 6]
Intersection:[4 5]


In [115]:
# Q20.3: Find the union of two arrays using np.union1d()
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
union = np.union1d(a1,a2)
print(f"A1:{a1}")
print(f"A2:{a2}")
print(f"Union:{union}")

A1:[1 2 3]
A2:[4 5 6]
Union:[1 2 3 4 5 6]


In [116]:
# Q20.4: Find elements in first array but not in second using `np.setdiff1d()`
a1 = np.array([1,2,3,4,5])
a2 = np.array([4,5,6])
setdiff = np.setdiff1d(a1,a2)
print(f"A1:{a1}")
print(f"A2:{a2}")
print(f"Setdiff:{setdiff}")

A1:[1 2 3 4 5]
A2:[4 5 6]
Setdiff:[1 2 3]


In [117]:
# Q20.5: Find the symmetric difference between two arrays using `np.setxor1d()`
a1 = np.array([1,2,3,4,5])
a2 = np.array([4,5,6])
symmetric_diff = np.setxor1d(a1,a2)
print(f"A1:{a1}")
print(f"A2:{a2}")
print(f"Symmetric Diff:{symmetric_diff}")

A1:[1 2 3 4 5]
A2:[4 5 6]
Symmetric Diff:[1 2 3 6]
