In [2]:
import numpy as np

# Manually created array: [Store ID, Sales, Customers, Inventory, Returns]
retail_data = np.array([
    [1, 25000, 300, 1200, 10],
    [2, 32000, 450, 1500, 15],
    [3, 28000, 380, 1100, 8],
    [4, 41000, 500, 1600, 20],
    [5, 35000, 420, 1400, 12],
    [6, 27000, 360, 1300, 9],
    [7, 39000, 480, 1700, 18],
    [8, 30000, 400, 1250, 14],
    [9, 45000, 550, 1800, 25],
    [10, 33000, 410, 1450, 11]
])
print(retail_data)


[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


# Retail Data – Business Questions (for `retail_data`)

**Assumed columns:** `[StoreID, Sales, Customers, Inventory, Returns]`

## Basic Performance Analysis
1. What is the **total revenue** generated across all stores?
2. Which store recorded the **highest sales**?
3. Which store recorded the **lowest sales**?
4. What is the **average daily sales** per store?
5. How many stores achieved sales **above ₹35,000**?

## Customer Insights
6. Which store had the **highest customer footfall**?
7. What is the **average number of customers** per store?
8. How many stores have **more than 450 customers**?
9. Which store has the **lowest customer count**?
10. Is there any store where **high sales do not correspond to high customers**?

## Inventory & Returns Analysis
11. What is the **total inventory** across all stores?
12. Which store has the **highest inventory stock**?
13. How many stores have **inventory less than 1300 units**?
14. Which store has the **highest return rate** (returns ÷ inventory)?
15. Which stores have **returns greater than 15 units**?

## Sales & Customer Correlation
16. Is there a **positive correlation** between sales and customers?
17. Which store has **high customer visits but low sales**?
18. Which store has **low customers but high sales**?
19. How many stores have **sales per customer above ₹90**?
20. Which stores could **benefit from customer acquisition campaigns** (low customers, high inventory)?

## Profitability & Growth
21. If profit margin is **20% of sales**, what is the **profit per store**?
22. Which store has the **highest profit**?
23. Which store has the **lowest profit**?
24. If sales increase by **10% next month**, what are the **new sales figures**?
25. How will **total profit** change with the 10% sales increase?

## Operational Strategy
26. Which stores need **inventory restocking** based on sales and current stock?
27. Which stores show **high returns percentage** and might require **quality checks**?
28. Which store is the **best performer overall** (sales, customers, inventory turnover)?
29. Which store is the **worst performer overall**?
30. Which stores can be considered for **expansion** based on strong sales and customer metrics?


In [3]:
print(retail_data)


[[    1 25000   300  1200    10]
 [    2 32000   450  1500    15]
 [    3 28000   380  1100     8]
 [    4 41000   500  1600    20]
 [    5 35000   420  1400    12]
 [    6 27000   360  1300     9]
 [    7 39000   480  1700    18]
 [    8 30000   400  1250    14]
 [    9 45000   550  1800    25]
 [   10 33000   410  1450    11]]


In [12]:

#1.What is the total revenue generated across all stores?

total_revenue = retail_data[:,1].sum()* retail_data[:,3].sum()
print(total_revenue)

4790500000


In [119]:
#2.Which store recorded the highest sales?

retail_data[:,1].argmax()+1

np.int64(9)

In [120]:
#3.Which store recorded the lowest sales?

retail_data[:,1].argmin()+1


np.int64(1)

In [121]:
#4.What is the average daily sales per store?

retail_data[:,1].mean()

np.float64(33500.0)

In [122]:
#5.How many stores achieved sales above ₹35,000?

count = np.sum(retail_data[:,1]>35000)
print("The total stores are:",count)


The total stores are: 3


In [123]:
# 6.Which store had the highest customer footfall?

retail_data[:,2].argmax()+1

np.int64(9)

In [124]:
#7.What is the average number of customers per store?

retail_data[:,2].mean()

np.float64(425.0)

In [125]:
#8.How many stores have more than 450 customers ?

count1 = np.sum(retail_data[:,2]>450)
print("The total stores are:",count1)

The total stores are: 3


In [126]:
#9.Which store has the lowest customer count ?

retail_data[:,2].argmin()+1

np.int64(1)

In [127]:
#10.Is there any store where high sales do not correspond to high customers 

avg_sales = np.mean(retail_data[:, 1])
avg_customers = np.mean(retail_data[:,2])

condition = (retail_data[:,1]>avg_sales) & (retail_data[:,2]<avg_customers)

result = retail_data[condition, [0,1,2]]

print("avg sales:", avg_sales)
print("avg customers:", avg_customers)
print("stores:", result)


avg sales: 33500.0
avg customers: 425.0
stores: [    5 35000   420]


In [128]:

# 11. What is the total inventory across all stores?

retail_data[:,3].sum()

np.int64(14300)

In [129]:
# 12. Which store has the highest inventory stock ?

retail_data[:,3].argmax()+1

np.int64(9)

In [130]:
# 13. How many stores have inventory less than 1300 units ?

count2 = np.sum(retail_data[:,3]<1300)
print("The total stores are:",count2)


The total stores are: 3


In [131]:

# 14. Which store has the highest return rate (returns ÷ inventory)?

return_rates = retail_data[:,4] / retail_data[:,3]
print(return_rates)

retail_data[:,4].argmax()+1


[0.00833333 0.01       0.00727273 0.0125     0.00857143 0.00692308
 0.01058824 0.0112     0.01388889 0.00758621]


np.int64(9)

In [132]:
# 15. Which stores have returns greater than 15 units ?

count3 = retail_data[retail_data[:,4]>15, 0]
print(count3)

[4 7 9]


In [21]:
# 16. Is there a positive correlation between sales and customers?

sales1 = retail_data[:, 1]
customers1 = retail_data[:, 2]

correlation = np.corrcoef(sales1,customers1)[0,1]
print(correlation)

0.9593636912502479


In [134]:
# 17. Which store has high customer visits but low sales ?

customers = retail_data[:,2].mean()
sales = retail_data[:,1].mean()

stores = retail_data[(retail_data[:,2]<customers) & (retail_data[:,1]>sales),0]
print("The store is:",stores)


The store is: [5]


In [135]:
# 18. Which store has low customers but high sales ?
customers = retail_data[:,2].mean()
sales = retail_data[:,1].mean()

store1 = retail_data[(retail_data[:,2]>customers) & (retail_data[:,1]<sales),0]
print(store1)

[2]


In [136]:
# 19. How many stores have sales per customer above ₹90 ?

div = retail_data[:,1]/ retail_data[:,2]
store2 = (div>90).sum()
print(store2)

0


In [138]:
# 20. Which stores could benefit from customer acquisition campaigns (low customers, high inventory)?

avg_customers = np.mean(retail_data[:, 2])
avg_inventory = np.mean(retail_data[:, 3])

conditions= (retail_data[:, 2] < avg_customers) & (retail_data[:, 3] > avg_inventory)

stores_campaign = retail_data[conditions, [0, 2, 3]]  

print("Avg Customers:", avg_customers)
print("Avg Inventory:", avg_inventory)
print("Stores to target:", stores_campaign)


Avg Customers: 425.0
Avg Inventory: 1430.0
Stores to target: [  10  410 1450]


In [139]:
# 21. If profit margin is 20% of sales , what is the **profit per store**?

profit = 0.2 * retail_data[:,1]

profit_for_store = np.column_stack((retail_data[:, 0], profit)).astype(int)

print("profit for sales:\n", profit_for_store)



profit for sales:
 [[   1 5000]
 [   2 6400]
 [   3 5600]
 [   4 8200]
 [   5 7000]
 [   6 5400]
 [   7 7800]
 [   8 6000]
 [   9 9000]
 [  10 6600]]


In [140]:

# 22. Which store has the highest profit? 

profit = 0.2 * retail_data[:,1]
highest_profit = profit.argmax()+1

print("Store ID:",highest_profit)





Store ID: 9


In [141]:
# 23. Which store has the lowest profit?

profit = 0.2 * retail_data[:,1]
lowest_profit = profit.argmin()+1

print("Store ID:",lowest_profit)

Store ID: 1


In [142]:
# 24. If sales increase by 10% next month, what are the **new sales figures**?


sales = retail_data[:, 1]
new_sales = sales * 1.1

new_sales_per_store = np.column_stack((retail_data[:, 0].astype(int), new_sales.astype(int) ))

print(new_sales_per_store)



[[    1 27500]
 [    2 35200]
 [    3 30800]
 [    4 45100]
 [    5 38500]
 [    6 29700]
 [    7 42900]
 [    8 33000]
 [    9 49500]
 [   10 36300]]


In [143]:
# 25. How will total profit change with the 10% sales increase?

profit_change = 0.2*0.1*retail_data[:,1].sum()
print(int(profit_change))

6700


In [145]:
# 26. Which stores need inventory restocking based on sales and current stock?

avg_sales = retail_data[:,1].mean()
avg_inventory = retail_data[:,3].mean()

condition1 = (retail_data[:,1]> avg_sales) & (retail_data[:,3] < avg_inventory)

restocking = retail_data[condition,[0,1,3]]

print("Store needing restocking:\n", restocking)

 

Store needing restocking:
 [    5 35000  1400]


In [146]:
# 27. Which stores show high returns percentage and might require **quality checks**?

returns = retail_data[:, 4]
inventory = retail_data[:, 3]

return_percent = (returns / inventory) * 100
avg_return_percent = np.mean(return_percent)

condition = return_percent > avg_return_percent
quality_check_stores = np.column_stack((retail_data[condition, 0], return_percent[condition]))

print("Average Return %:", avg_return_percent)
print("Stores needing quality checks:\n", quality_check_stores)


Average Return %: 0.9686389718012436
Stores needing quality checks:
 [[2.         1.        ]
 [4.         1.25      ]
 [7.         1.05882353]
 [8.         1.12      ]
 [9.         1.38888889]]


In [ ]:

# 28. Which store is the best performer overall (sales, customers, inventory turnover)?

inventory_turnover = retail_data[:, 1] / retail_data[:, 4]

# Normalize metrics (min-max scaling)
sales_norm = (retail_data[:, 1] - retail_data[:, 1].min()) / (retail_data[:, 1].max() - retail_data[:, 1].min())
customers_norm = (retail_data[:, 2] - retail_data[:, 2].min()) / (retail_data[:, 2].max() - retail_data[:, 2].min())
turnover_norm = (inventory_turnover - inventory_turnover.min()) / (inventory_turnover.max() - inventory_turnover.min())

# Composite score (equal weights)
overall_score = sales_norm + customers_norm + turnover_norm

# Find best performer
best_index = np.argmax(overall_score)
best_store = retail_data[best_index]

print(f"Best performer overall: Store ID {int(best_store[0])}")
print(f"Sales: {best_store[1]}, Customers: {best_store[2]}, Inventory: {best_store[4]}")

Best performer overall: Store ID 9
Sales: 45000, Customers: 550, Inventory: 25


In [24]:

# 29. Which store is the worst performer overall ?

inventory_turnover = retail_data[:, 1] / retail_data[:, 4]

# Normalize metrics (min-max scaling)
sales_norm = (retail_data[:, 1] - retail_data[:, 1].min()) / (retail_data[:, 1].max() - retail_data[:, 1].min())
customers_norm = (retail_data[:, 2] - retail_data[:, 2].min()) / (retail_data[:, 2].max() - retail_data[:, 2].min())
turnover_norm = (inventory_turnover - inventory_turnover.min()) / (inventory_turnover.max() - inventory_turnover.min())

# Composite score (equal weights)
overall_score = sales_norm + customers_norm + turnover_norm

# Find worst performer
worst_index = np.argmin(overall_score)
worst_store = retail_data[worst_index]

print(f"Worst performer overall: Store ID {int(worst_store[0])}")
print(f"Sales: {worst_store[1]}, Customers: {worst_store[2]}, Inventory: {worst_store[4]}")

Worst performer overall: Store ID 1
Sales: 25000, Customers: 300, Inventory: 10


In [27]:

# 30. Which stores can be considered for expansion based on strong sales and customer metrics?

avg_sales = retail_data[:,1].mean()
avg_customers = retail_data[:,2].mean()
condition2 = retail_data[(retail_data[:,1]>avg_sales) & (retail_data[:,2]>avg_customers)]
print(condition2)

[[    4 41000   500  1600    20]
 [    7 39000   480  1700    18]
 [    9 45000   550  1800    25]]
